apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: rhacm-bucket
      endpoint: minio.minio.svc:9000
      insecure: true
      access_key: myaccesskey
      secret_key: mysecretkey